services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  airflow-init:
    build: .
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=heyrcg_secret_key_12345
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"

  airflow-webserver:
    build: .
    restart: always
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/bq-sa.json
      - GCP_PROJECT=${GCP_PROJECT}
      - GCP_DATASET=${GCP_DATASET}
      - AIRFLOW__WEBSERVER__SECRET_KEY=heyrcg_secret_key_12345
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./credentials:/opt/airflow/credentials
      - .:/opt/airflow/dbt
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: webserver

  airflow-scheduler:
    build: .
    restart: always
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/bq-sa.json
      - GCP_PROJECT=${GCP_PROJECT}
      - GCP_DATASET=${GCP_DATASET}
      - AIRFLOW__WEBSERVER__SECRET_KEY=heyrcg_secret_key_12345
    volumes:
      - ./dags:/opt/airflow/dags
      - ./credentials:/opt/airflow/credentials
      - .:/opt/airflow/dbt
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
